app/todo/forms.py
#! /usr/bin/env python2
# -*-coding:utf-8-*-


from flask_wtf import FlaskForm
from wtforms import RadioField, SubmitField, StringField
from wtforms.validators import DataRequired, Length


class TodoListForm(FlaskForm):
    title = StringField(u'内容', validators=[DataRequired(), Length(1, 64)])
    status = RadioField(u'是否完成', validators=[DataRequired()],  choices=[
                        ("1", u'完成'), ("0", u'待办')])
    submit = SubmitField(u'提交')

app/todo/__init__.py
#! /usr/bin/env python2
# -*-coding:utf-8-*-


from flask import Blueprint


todo = Blueprint('todo', __name__)


from . import views, errors

app/todo/views.py
#! /usr/bin/env python2
# -*-coding:utf-8-*-


from . import todo
from .. import db
from ..models import TodoList
from flask_login import login_required, current_user
# from .forms import TodoListForm, LoginForm, RegisterForm
from .forms import TodoListForm
from flask import render_template, redirect, request, url_for, flash


@todo.route('/', methods=['GET', 'POST'])
@login_required
def show_todo_list():
    form = TodoListForm()
    if request.method == 'GET':
        todolists = TodoList.query.filter_by(
            user_id=current_user.id).all()
        return render_template('todo/index.html', todolists=todolists,
                               form=form, username=current_user.username)
    else:
        if form.validate_on_submit():
            todolist = TodoList(
                user_id=current_user.id, title=form.title.data,
                status=form.status.data)
            try:
                db.session.add(todolist)
                db.session.commit()
                flash(u'你成功增加了待办事项')
            except:
                db.session.rollback()
                raise
        else:
            flash(u'请先登录')
        return redirect(url_for('todo.show_todo_list'))


@todo.route('/delete/<int:id>')
@login_required
def delete_todo_list(id):
    todolist = TodoList.query.filter_by(id=id).first_or_404()
    try:
        db.session.delete(todolist)
        db.session.commit()
        flash(u'你成功的删除了待办事项')
        return redirect(url_for('todo.show_todo_list'))
    except:
        db.session.rollback()
        raise


@todo.route('/change/<int:id>', methods=['GET', 'POST'])
@login_required
def change_todo_list(id):
    if request.method == 'GET':
        todolist = TodoList.query.filter_by(id=id).first_or_404()
        form = TodoListForm()
        form.title.data = todolist.title
        form.status.data = str(todolist.status)
        return render_template('todo/modify.html', form=form)
    else:
        form = TodoListForm()
        if form.validate_on_submit():
            todolist = TodoList.query.filter_by(id=id).first_or_404()
            todolist.title = form.title.data
            todolist.status = form.status.data
            try:
                db.session.commit()
                flash(u'你成功修改了待办事项')
            except:
                db.session.rollback()
        else:
            flash(form.errors)
        return redirect(url_for('todo.show_todo_list'))

app/templates/todo/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<h1 align="center">Hello,{{username}}</h1>
<table class="table table-hover table-bordered">
    <thead>
        <th class="active">编号</th>
        <th class="active">描述</th>
        <th class="active">是否完成</th>
        <th class="active">创建时间</th>
        <th class='active'>操作</th>
    </thead>
    <tbody>
        {% for todo in todolists %}

            <!-- tr -->
            {% if todo.status %} <tr class="success">
            {% else %} <tr class="info"> {% endif %}
                <td>{{ loop.index }}</td>
                <td>{{ todo.title }}</td>
                <td>{{ todo.status }}</td>
                <td>{{ todo.create_time }}</td>
                <td>
                    {% if todo.status %}
                    <a href="{{ url_for('todo.delete_todo_list', id=todo.id) }}" class="btn btn-danger" role ="button">删除</a>
                    {% else %}
                    <a href="{{ url_for('todo.change_todo_list', id=todo.id) }}" class="btn btn-success" role ="button">修改</a>
                    {% endif %}
                </td>

            </tr>
        {% endfor %}

    </tbody>
</table>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal"> 添加 </button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog"> <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel" align="center">添加新的待办事项</h4>
      </div>

      <div class="modal-body">
          <div class="row">
              <div class="col-md-8 col-md-offset-2"> {{ wtf.quick_form(form, form_type="horizontal") }} </div>
          </div>
      </div> <!-- modal body -->

    </div> </div>
</div>


{% endblock %}

app/templates/todo/modify.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}

<div class="row">
    <h4 class="modal-title" id="myModalLabel" align="center"></h4>
    <div class="col-md-8 col-md-offset-2"> {{ wtf.quick_form(form, form_type="horizontal") }} </div>
</div>

{% endblock %}