app/main/forms.py
#! /usr/bin/env python2
# -*-coding:utf-8-*-


from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField,  TextAreaField,\
    SelectField, BooleanField
from wtforms.validators import DataRequired
from flask_wtf.file import FileField, FileAllowed, FileRequired
from .. import photos


class CommentForm(FlaskForm):
    # body = StringField('', validators=[DataRequired()])
    # 必须是TextAreaField这种才能使用富文本编辑器，这个问题找死我了
    body = TextAreaField(u'内容', validators=[DataRequired()])
    submit = SubmitField(u'提交评论')


class NewAlbumForm(FlaskForm):
    title = StringField(u'标题')
    about = TextAreaField(u'介绍', render_kw={'rows': 8})
    photo = FileField(u'图片(请勿上传全中文名的图片)', validators=[
        FileRequired(u'你还没有选择图片！'),
        FileAllowed(photos, u'只能上传图片！')
    ])
    asc_order = SelectField(u'显示顺序',
                            choices=[('True', u'按上传时间顺序排列'), ('False', u'按上传时间倒序排列')])
    no_public = BooleanField(u'私密相册（勾选后相册仅自己可见）')
    no_comment = BooleanField(u'禁止评论')
    submit = SubmitField(u'提交')


class AddPhotoForm(FlaskForm):
    photo = FileField(u'图片', validators=[
        FileRequired(),
        FileAllowed(photos, u'只能上传图片！')
    ])
    submit = SubmitField(u'提交')


class EditAlbumForm(FlaskForm):
    title = StringField(u'标题')
    about = TextAreaField(u'介绍', render_kw={'rows': 8})
    asc_order = SelectField(u'显示顺序',
                            choices=[("1", u'按上传时间倒序排列'), ("0", u'按上传时间倒序排列')])
    no_public = BooleanField(u'私密相册（右侧滑出信息提示：勾选后相册仅自己可见）')
    no_comment = BooleanField(u'允许评论')
    submit = SubmitField(u'提交')

app/main/__init__.py
#! /usr/bin/env python2
# -*-coding:utf-8-*-


from flask import Blueprint


main = Blueprint('main', __name__)


from . import views, errors
from ..models import Permission


@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

app/main/views.py
#! /usr/bin/env python2
# -*-coding:utf-8-*-


import os
import time
import PIL
import hashlib
from PIL import Image
from flask_login import login_required, current_user
from flask import render_template, request, redirect, flash, url_for,\
    current_app, send_from_directory, abort
from ..decorators import admin_required, permission_required
from ..models import Article, Comment, User, Permission, Album, Photo, Category
from .forms import CommentForm, NewAlbumForm, EditAlbumForm, AddPhotoForm
from . import main
from .. import db, photos


@main.route('/')
def index():
    categorys = Category.query.all()
    page = request.args.get('page', 1, type=int)
    pagination = Article.query.paginate(
        page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
        error_out=False)
    articles = pagination.items
    return render_template('main/index.html',
                           list=articles,
                           categorys=categorys,
                           pagination=pagination)


@main.route('/read/<int:id>', methods=['POST', 'GET'])
def read(id):
    # the_article = Article.query.filter_by(id=request.args.get('id')).first()
    the_article = Article.query.get_or_404(id)
    if the_article is not None:
        return render_template('main/read.html', list=the_article)
    flash(u'未找到相关文章')
    return redirect(url_for('main.index'))


@main.route('/listarticle/<int:id>')
def listarticle(id):
    page = request.args.get('page', 1, type=int)
    pagination = Article.query.filter_by(user_id=id).paginate(
        page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
        error_out=False)
    articles = pagination.items
    return render_template('main/article.html', list=articles, id=id,
                           pagination=pagination) \
        # 此处耗费了我好多好多脑细胞，要把id传进去，不然每次的翻页请求id不能正常传进去
    # 而且分页模板那个地方，也要传进去id（因为改变成了路由带有参数）


@main.route('/user/<username>')
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    pagination = user.articles.paginate(
        page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
        error_out=False)
    articles = pagination.items
    return render_template('admin/user.html', user=user, list=articles,
                           pagination=pagination)


@main.route('/comment/<int:id>', methods=['POST', 'GET'])
@login_required
def comment(id):
    the_article = Article.query.get_or_404(id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(body=form.body.data,
                          article=the_article,
                          user=current_user._get_current_object()
                          )
        # comment = Comment(body=form.body.data)
        db.session.add(comment)
        db.session.commit()
        flash(u'你已成功添加评论')
        return redirect(url_for('main.read', id=id))
    return render_template('main/comment.html', form=form)


@main.route('/follow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def follow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash(u'无效用户')
        return redirect(url_for('main.index'))
    if current_user.is_following(user):
        flash(u'你已经关注此用户')
        return redirect(url_for('admin.user', username=username))
    current_user.follow(user)
    flash(u'你正在关注 %s.' % username)
    return redirect(url_for('.user', username=username))


@main.route('/unfollow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user.')
        return redirect(url_for('main.index'))
    if not current_user.is_following(user):
        flash(u'你没有关注此用户')
        return redirect(url_for('main.user', username=username))
    current_user.unfollow(user)
    flash(u'你取消关注 %s' % username)
    return redirect(url_for('main.user', username=username))


@main.route('/followers/<username>')
def followers(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash(u'无效用户')
        return redirect(url_for('main.index'))
    page = request.args.get('page', 1, type=int)
    pagination = user.followers.paginate(
        page, per_page=current_app.config['FLASKY_FOLLOWERS_PER_PAGE'],
        error_out=False)
    follows = [{'user': item.follower}
               for item in pagination.items]
    return render_template('following.html',
                           user=user,
                           endpoint='.followers',
                           pagination=pagination,
                           follows=follows)


@main.route('/followed-by/<username>')
def followed_by(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash(u'无效用户')
        return redirect(url_for('main.index'))
    page = request.args.get('page', 1, type=int)
    pagination = user.followed.paginate(
        page, per_page=current_app.config['FLASKY_FOLLOWERS_PER_PAGE'],
        error_out=False)
    follows = [{'user': item.followed}
               for item in pagination.items]
    return render_template('followed.html',
                           user=user,
                           endpoint='.followed_by',
                           pagination=pagination,
                           follows=follows)


def save_image(files):
    photo_amount = len(files)
    if photo_amount > 50:
        flash(u'抱歉每次上传不超过50张！', 'warning')
        return redirect(url_for('main.new_album'))
    images = []
    for img in files:
        filename = hashlib.md5(current_user.username +
                               str(time.time())).hexdigest()[:10]
        image = photos.save(img, name=filename + '.')
        file_url = photos.url(image)
        url_s = image_resize(image, 800)
        url_t = image_resize(image, 300)
        images.append((file_url, url_s, url_t))
    return images


img_suffix = {
    300: '_t',  # thumbnail
    800: '_s'  # show
}


def image_resize(image, base_width):
    #: create thumbnail
    filename, ext = os.path.splitext(image)
    img = Image.open(photos.path(image))
    if img.size[0] <= base_width:
        return photos.url(image)
    w_percent = (base_width / float(img.size[0]))
    h_size = int((float(img.size[1]) * float(w_percent)))
    img = img.resize((base_width, h_size), PIL.Image.ANTIALIAS)
    img.save(os.path.join(current_app.config[
             'UPLOADED_PHOTOS_DEST'], filename + img_suffix[base_width] + ext))
    return url_for('.uploaded_file', filename=filename + img_suffix[base_width] + ext)


@main.route('/<username>', methods=['GET', 'POST'])
@login_required
def albums(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)

    page = request.args.get('page', 1, type=int)
    pagination = user.albums.order_by(Album.timestamp.desc()).paginate(
        page, per_page=current_app.config['FANXIANGCE_ALBUMS_PER_PAGE'], error_out=False)
    albums = pagination.items

    photo_count = sum([len(album.photos.all()) for album in albums])
    album_count = len(albums)

    return render_template('main/albums.html',
                           user=user,
                           albums=albums,
                           album_count=album_count,
                           photo_count=photo_count,
                           pagination=pagination)


@main.route('/new-album', methods=['GET', 'POST'])
@login_required
def new_album():
    form = NewAlbumForm()
    if form.validate_on_submit():  # current_user.can(Permission.CREATE_ALBUMS)
        if request.method == 'POST' and 'photo' in request.files:
            images = save_image(request.files.getlist('photo'))

        title = form.title.data
        about = form.about.data
        author = current_user._get_current_object()
        no_public = form.no_public.data
        no_comment = form.no_comment.data
        album = Album(title=title, about=about,
                      cover=images[0][2], author=author,
                      no_public=no_public, no_comment=no_comment)
        db.session.add(album)

        for url in images:
            photo = Photo(url=url[0],
                          url_s=url[1],
                          url_t=url[2],
                          album=album,
                          author=current_user._get_current_object())
            db.session.add(photo)
        db.session.commit()
        flash(u'相册创建成功！', 'success')
        return redirect(url_for('.edit_photo', id=album.id))
    return render_template('main/new_album.html', form=form)


@main.route('/uploads/<filename>')
def uploaded_file(filename):
    return send_from_directory(current_app.config['UPLOADED_PHOTOS_DEST'],
                               filename)


@main.route('/edit-photo/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_photo(id):
    album = Album.query.get_or_404(id)
    photos = album.photos.order_by(Photo.order.asc())
    if request.method == 'POST':
        for photo in photos:
            photo.about = request.form[str(photo.id)]
            photo.order = request.form["order-" + str(photo.id)]
            db.session.add(photo)
        album.cover = request.form['cover']
        db.session.add(album)
        db.session.commit()
        flash(u'更改已保存。', 'success')
        return redirect(url_for('.album', id=id))
    enu_photos = []
    for index, photo in enumerate(photos):
        enu_photos.append((index, photo))

    return render_template('main/edit_photo.html',
                           album=album,
                           photos=photos,
                           enu_photos=enu_photos)


@main.route('/album/<int:id>')
def album(id):
    album = Album.query.get_or_404(id)
    # display default cover when an album is empty
    placeholder = 'http://p1.bpimg.com/567591/15110c0119201359.png'

app/templates/main/add_photo.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}创建{% endblock %}
{% block page_content %}
<div class="page-header">
    <h1>添加照片</h1>
</div>

<ol class="breadcrumb" id="navigation">
    <li><a href="{{ url_for('.albums', username=album.author.username) }}">{% if current_user == album.author %}我{% else %}{{ album.author.name }}{% endif %}的相册</a></li>
    <li><a href="{{ url_for('.album', id=album.id) }}">《{{ album.title }}》</a></li>
    <li class="active">添加照片</li>
    <li class="pull-right"><a href="{{ url_for('.album', id=album.id) }}">返回相册</a></li>
</ol>

<div class="loader"></div>
<div class="mask-bg"></div>

<div class="col-md-6">
    <form class="form form-horizontal" method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        {{ wtf.form_field(form.photo, multiple="multiple") }}
        {{ wtf.form_field(form.submit) }}
    </form>
</div>
{% endblock %}

{% block scripts %}
{{super()}}
<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script>
    // display loading animation
    $('#submit').click(function() {
        $('.mask-bg').show();
        $('.loader').show();
    })
</script>
{% endblock %}

app/templates/main/albums.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}{{ user.username }}的相册{% endblock %}

{% block page_content %}
<div class="row">
    <div class="col-md-9">
        <div class="text-center container-fluid">
            {% if album_count == 0 %}
            {% if current_user == user %}
            <h3>你还没有相册，快来<a href="{{ url_for('main.new_album') }}">创建</a>一个吧！</h3>
            {% else %}
            <h3>他/她还没有创建相册。</h3>
            {% endif %}
            {% endif %}
            <div class="row text-center">
                {% for album in albums %}
                {% if not album.no_public or current_user == user%}
                <div class="album col-md-3">
                    <div class="album-frame">
                        <a class="thumbnail album-thumbnail" href="{{ url_for('main.album', id=album.id) }}">
                            <img class="img-responsive portrait" src="{{ album.cover }}">
                        </a>
                    </div>
                    <div class="info">
                        <h5><a href="{{ url_for('.album', id=album.id) }}">{{ album.title }}</a></h5>
                        <span>{{ album.photos.count() }}张图片</span>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
        <hr>
        <div class="container-fluid col-md-3">
        <div class="data-area">
            <i class="glyphicon glyphicon-user"></i>
            关注者<a href="{{ url_for('.followers', username=user.username) }}"><span class="badge">{{ user.followers.count()-1}}</span></a>
            <br>
            <i class="glyphicon glyphicon-user"></i>
            正在关注<a href="{{ url_for('.followed_by', username=user.username) }}"><span class="badge">{{ user.followed.count()-1}}</span></a>
            <br>
            <i class="glyphicon glyphicon-th-large"></i> 相册{{ album_count }}
            <br>
            <i class="glyphicon glyphicon-picture"></i> 照片{{ photo_count }}
            <br>
            {% if user.location %}
            <i class="glyphicon glyphicon-map-marker"></i>
            <a href="http://maps.google.com/?q={{ user.location }}">{{ user.location }}</a><br>
            {% endif %}
            {% if user.website %}
            <i class="glyphicon glyphicon-link"></i>
            <a href="{{ user.website }}" target="_blank">{{ user.website }}</a><br>
            {% endif %}
            {%if current_user==user%}
            <a href="{{ url_for('main.new_album') }}"><button type="button" class="btn btn-primary btn-sm" data-toggle="modal"
                                     data-target="#myModal">创建相册</button></a>
                                     {%endif%}

        </div>
      </div>

        {% if user.about_me %}
        <hr>
        <div class="about-area">
            {{ about_me|safe }}
        </div>
        {% endif %}
    </div>
  </div>
</div>

<div class="text-center">
    {{ macros.pagination_widget(pagination, '.albums', username=user.username) }}
</div>
<hr>
{% endblock %}

app/templates/main/article.html
{% extends 'base.html' %}
{% import "_macros.html" as macros %}

{% block page_content %}
{% block head %}
{{ super() }}
<script src="//cdn.ckeditor.com/4.5.11/full/ckeditor.js"></script>
<link href="/static/css/styles.css" type="text/css" rel="stylesheet">
{% endblock %}
    <div class="col-md-8">
        {% for foo in list %}
        <div class="blog-main">
          <div class="post-summary">
            <div class="post-head">
              <h3><a href="{{ url_for('main.read' , id=foo.id) }}">{{foo.title}}</a></h3>
            </div>
            <h6><a href="{{url_for('main.listarticle',id=foo.user_id)}}"><span class="label label-info">{{foo.user.username}}</span></a>&nbsp;<span class="glyphicon glyphicon-comment"></span>&nbsp;&nbsp;{{foo.comments.count()}} Comments</h6>
            <div class="post-body">
                <p>{{foo.body|safe|truncate(305,True)}}</p>
            </div>
              <div class="post-footer">
              <a href="{{ url_for('main.read' , id=foo.id) }}">
                  <button class="btn btn-default" type="button">阅读全文</button>
              </a>
              </div>
        </div>
        {% endfor %}
    </div>
    {% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, 'main.listarticle',id=id) }}
    <!-- #注意此处要把参数传递进去 -->
</div>
{% endif %}
{% endblock %}

app/templates/main/articlebak.html
{% extends 'base.html' %}
{% block page_content %}
<div class="container">
       {% for foo in list %}
           <div class="act">
                 <div class="col-md-12">
                     <h2><a href="{{ url_for('main.read' , id=foo.id) }}"></a>{{ foo.title }}</h2>
                     <hr>
                     <p>{{ foo.create_time }} | {{ foo.category.name }}</p>
                     <p>{{foo.body|safe}}</p>
                 </div>
           </div>
       {% endfor %}
   </div>
{% endblock %}

app/templates/main/articletest.html
{% extends 'base.html' %}
{% import "_macros.html" as macros %}

{% block page_content %}
{% block head %}
{{ super() }}
<script src="//cdn.ckeditor.com/4.5.11/full/ckeditor.js"></script>
<link href="/static/css/styles.css" type="text/css" rel="stylesheet">
{% endblock %}
    <div class="col-md-8">
        {% for foo in list %}
        <div class="blog-main">
          <div class="post-summary">
            <div class="post-head">
              <h3><a href="{{ url_for('main.read' , id=foo.id) }}">{{foo.title}}</a></h3>
            </div>
            <h6><a href="{{url_for('main.listarticle',id=foo.user_id)}}"><span class="label label-info">{{foo.user.username}}</span></a>&nbsp;&nbsp;{{foo.comments.count()}} Comments</h6>
            <div class="post-body">
                <p>{{foo.body|safe|truncate(305,True)}}</p>
            </div>
              <div class="post-footer">
              <a href="{{ url_for('main.read' , id=foo.id) }}">
                  <button class="btn btn-default" type="button">阅读全文</button>
              </a>
              </div>
        </div>
        {% endfor %}
    </div>
    {% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, 'main.listarticle',id=id) }}
    <!-- #注意此处要把参数传递进去 -->
</div>
{% endif %}
{% endblock %}

app/templates/main/category_articles.html
{% extends "base.html" %}
{ % import "_macros.html" as macros % }
{% import "_macros.html" as macros %}
{% block title %}{{ category.name }}{% endblock %}
{% block head %}
{{ super() }}
<script src="//cdn.ckeditor.com/4.5.11/full/ckeditor.js"></script>
<link href="/static/css/styles.css" type="text/css" rel="stylesheet">
{% endblock %}


{% block page_content %}
{%include "_articles.html"%}
{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, 'main.category', id=category.id) }}
</div>
{% endif %}
{% endblock %}

app/templates/main/comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block head %}
{{ super() }}
<script src="//cdn.ckeditor.com/4.5.11/full/ckeditor.js"></script>
{% endblock %}
{% block page_content %}
    <div class="col-md-12">
    <form class="form" method="POST">
    {{ form.hidden_tag() }}
    {{ wtf.form_field(form.body,class="ckeditor")}}
    {{ wtf.form_field(form.submit) }}
    </form>
    </div>
{% endblock %}

app/templates/main/edit_album.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}编辑相册{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>相册与图片设置</h1>
</div>
<ol class="breadcrumb" id="navigation">
    <li><a href="{{ url_for('.index') }}" target="_blank">首页</a></li>
    <li class="active">编辑相册信息</li>
    <li><a href="{{ url_for('.edit_photo', id=album.id) }}" target="_blank">照片编辑与排序</a></li>
    <li class="pull-right"><a href="{{ url_for('.album', id=album.id) }}">返回</a></li>
    <li class="pull-right"><a href="{{ url_for('.add_photo', id=album.id) }}" target="_blank">添加图片</a></li>
</ol>

<div class="row">
    <div class="col-md-6">
        <form class="form" method="POST">
          {{ form.hidden_tag() }}
          {{ wtf.form_field(form.title) }}
          {{ wtf.form_field(form.about) }}
          {{ wtf.form_field(form.asc_order) }}
          {% if album.is_public %}
          {{ wtf.form_field(form.no_public) }}
            {% else %}
            {{ wtf.form_field(form.no_public, checked) }}
            {% endif %}
            {% if album.can_comment %}
          {{ wtf.form_field(form.no_comment, checked) }}
            {% else %}
             {{ wtf.form_field(form.no_comment) }}
            {% endif %}
             <hr>
          {{ wtf.form_field(form.submit) }}
        </form>
    </div>
</div>
{% endblock %}

app/templates/main/edit_photo.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}编辑照片{% endblock %}
{% block head %}
{{super()}}
<link href="{{ url_for('static', filename='jquery-ui-1.12.1/jquery-ui.min.js') }}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>相册与图片设置</h1>
</div>
<ol class="breadcrumb" id="navigation">
    <li><a href="{{ url_for('.index') }}" target="_blank">首页</a></li>
    <li><a href="{{ url_for('.edit_album', id=album.id) }}" target="_blank">编辑相册信息</a></li>
    <li class="active">照片编辑与排序</li>
    <li class="pull-right"><a href="{{ url_for('.album', id=album.id) }}">返回</a></li>
    <li class="pull-right"><a href="{{ url_for('.add_photo', id=album.id) }}" target="_blank">添加图片</a></li>
</ol>

<form action="{{ url_for('.edit_photo', id=album.id) }}" method="POST">
    <div class="sort-area">
    <div class="row">
    <section id="wrapper">
	<ul class="images images-edit" id="images">
        {% for photo in enu_photos %}
		<li><div class="edit-thumbnail">
                <img class="img-responsive portrait" src="{{ photo[1].url_t }}" alt="Some description"/>
            </div><br>
            <textarea name="{{ photo[1].id }}" placeholder="添加描述" rows="3">{% if photo[1].about %}{{ photo[1].about }}{% endif %}</textarea>
            <input class="order" type="hidden" name="order-{{ photo[1].id }}" value="{{ photo[0] + 1 }}"><br>
            设为封面<input type="radio" name="cover" value="{{ photo[1].url_t }}" {% if photo[1].url_t == album.cover %}checked{% endif %}>
            <a href="#" data-href="{{ url_for('.delete_edit_photo', id=photo[1].id) }}" class="pull-right btn btn-danger btn-xs" data-toggle="modal" data-target="#confirm-delete">删除</a>
        </li>
        {% endfor %}
	</ul>
    </section>
    </div>
    <div class="row text-center">
        <hr>
        <input class="btn btn-success" type="submit" name="submit" value="提交">&nbsp;&nbsp;
        <a class="btn btn-default" href="{{ url_for('.album', id=album.id) }}">取消</a>
    </div>
    </div>
</form>

<!-- 图片删除确认弹窗 用于喜欢页面和上传页面-->
        <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog">
          <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    确定要删除这张图片？
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                 <a class="btn btn-danger btn-ok">确定</a>
              </div>
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
{% endblock %}

{% block scripts %}
{{super()}}
<script src="{{ url_for('static', filename='jquery-ui-1.12.1/jquery-ui.min.js') }}" type="text/javascript"></script>
<script src="{{ url_for('static', filename='js/core.js') }}" type="text/javascript"></script>
<script>
$('#confirm-delete').on('show.bs.modal', function(e) {
 $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href')); // redirect the url
 $(".btn-ok").click(function() {
    $(e.relatedTarget).parent().slideUp(); // delete the photo
    $('#confirm-delete .close').click(); // close modal
 });
});
</script>
{% endblock %}

app/templates/main/indextest.html
{% extends 'base.html' %}
{% block page_content %}
{% block head %}
{{ super() }}
<script src="//cdn.ckeditor.com/4.5.11/full/ckeditor.js"></script>
<link href="/static/css/styles.css" type="text/css" rel="stylesheet">
{% endblock %}
    <div class="col-md-8">
        {% for foo in list %}
        <div class="blog-main">
          <div class="post-summary">
            <div class="post-head">
              <h3><a href="{{ url_for('main.read' , id=foo.id) }}">{{foo.title}}</a></h3>
            </div>
            <h6><a href="{{url_for('main.listarticle',id=foo.user_id)}}"><span class="label label-info">{{foo.user.username}}</span></a>&nbsp;&nbsp;{{foo.comments.count()}} Comments</h6>
            <div class="post-body">
                <p>{{foo.body|safe|truncate(305,True)}}</p>
            </div>
              <div class="post-footer">
              <a href="{{ url_for('main.read' , id=foo.id) }}">
                  <button class="btn btn-default" type="button">阅读全文</button>
              </a>
              </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

app/templates/main/read.html
{% extends 'base.html' %}
{% block page_content %}
<div class="container">
       <div class="col-md-12">
           <h2>{{ list.title }}</h2>
           <hr>
           <p>{{ list.create_time }} | {{ list.category.name }}</p>
           {{ list.body|safe }}
         <hr>
         <h3>评论区</h3>
          <!-- <p>{{list.comments.body|safe}}</p> -->
          {% for foo in list.comments %}
          <h4><span class="label label-info">{{foo.user.username}}评论道:</span></h4>
          <p>{{foo.body|safe}}</p>
          {%endfor%}
           <a href="{{ url_for('main.comment',id=list.id) }}"><button class="btn btn-default" type="button" >写评论</button></a>
           <!-- button得放在a标签里面 -->
       </div>
</div>
{% endblock %}